language: java
sudo: false
jdk: oraclejdk8
before_install:
- chmod +x gradlew
install: 
- "./gradlew setupCIWorkspace"
script:
- "./gradlew build"
notifications:
  webhooks: https://sqbika.win/travis.php
deploy:
  provider: releases
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQC6XRRRXiupoK8BrXi6b/hWmM02hC8ummlcJzK/j/4xGgcJTEqEzTPEwitv6n/OF69XmnyBF7HBEpV4Ntgsky13ZrKRxxJ4xPHczbTw7CM3Jy+y69giDfiJqfClLaFEBSE9IDFnOvMbzO3Cs/5IehCOfaC4j9mKRN+nQhvqP1tPVX57TZOVqGVZIoD3ylW7+n1hq+4/lCpEF6aq/lNFr87sJa6yeheiaCEY4yR9bZYWnAgsgFYDSL0MyEC6rXDuyXbVNETRM9KoYmULPb6GekprJt7IIlbqNSJIX4rs2U7MUTnKWnhBeIIZo6CgmDI3Tsf7ZWrsr6V6Q6ZR4C6+puiSfcgHmaakoFVrTJUh0vdBIO04mllJ5XgvM5JMi9TvSF404LL++exWcL0HwdTdh1MGctRCI9AzEC65ehiVnHqpGz85gPSWBIvbtAPGKIhF6TEcMoMwfodbLR7aCLciT6Ag+c/szz7KFzEbBYJXWyQI+5YUkN7DceoaMJjL1ka+DQnpvDC/Ylsf7TDn3ilXdhsmhEEaxvsdLhYnHl56Yala5rh1xMLsIpog6v/VpiMHEjQrFO/NhvBODyhT/kxbpo1mtXehd9L3A9/P3G5jncnnm329ChJPSsKNYpI4aLa47c3CX0zo0YRNXToEPfIUGZAp9bYDnWN0+kQKMHFPZPylHQ==
  file: "build/libs/*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    repo: Sqbika/ArsMagica2
    branch: 1.12.2-Update
    tags: true
