language: java
sudo: false
jdk: oraclejdk8
before_install:
- chmod +x gradlew
install: 
- "./gradlew setupCIWorkspace"
script:
- "./gradlew build"
notifications:
  webhooks: http://sqbika.win/travis.php
deploy:
  provider: releases
  api_key:
    secure: U45CwkYyS7GgKHEqhurzHXWHfkQ9l42UWsqMOfoqt2KPrqT0rgtGhmOl0BxmhF12+i7cu21y+DiwULWHJ5tivrHqpo5l6YyglsqsUHaB4vNMc2iQh7oU38nBUmqVeNeNBKQHfzi+hTi2INggloOv/IBuyn4aA2kWUv7kllu0S1+TQO7gZsP7FljnYiR8CQG9TPguGxc5HEPdNgPtOk1a2XVxqf78RjPV1ThUIXqn7MxBDWMDwCYguwlwzzyNGcb5WuIaQZ8DpErr6S1scWiPM/fMiAObV3X25rRfYEES3cxCyS0xQVNjp5s/5WnumKyG3I7EJWMAHSWJAyhIqWPvyLgVOh4tJUkH8hjVOS+802TbSGbCnVgv+f6D/8UVLHzMeNk1GTbqnyNiXGvYLzClCxwkoLPWQkdIlW7lhnVc+WXr78P8/5SWHPpgqOV921tAIAEiyLYAkaa5egUKy7J6s1Wj9yeoQqL+To0XD/KE11GCgEXrLaafVXC4DdNN24WD43Odi73vzXU3RBltCNNhDKHtm3MgydXIROspRRKTgFi4UAnhmpi6mF9zwFfgP//eqqXanBL1Z2FCmsaokdtqm2wB3pVDv/JNy9JCiT0YeAEQAhMqiLNwlwgtSPyhLcD/jGOorOknBGiji2CXyA4AfCgBndtC7newN9kzPqFKIkI=
  file: "build/libs/*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    repo: EdwinMindcraft/ArsMagica2
    branch: 1.10.2
    tags: true
